package:
  format-version: "1.0.0"
  name: "spi_uhf_transceiver"
  type: "api"
  status: "production"
  required: false
  version: "v1.0.1"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.14.0"
    - name: "core"
      type: "package"
      version: "v3.11.1"
