package:
  format-version: "1.0.0"
  name: "spi_uhf_transceiver"
  type: "api"
  status: "beta"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.14.0"
    - name: "core"
      type: "package"
      version: "3.11.1"
